### ISSUE TITLE
Enhanced pyi file generation from the official docs

### ISSUE THREAD

**Issue by I-am-Future** [yzqin/isaacgym-stubs#2]
Hi Mr. Qin, 

Thank you for your isaacgym python stubs! It really helps me a lot!

Currently, the stubs provides basic type hints, but I think there are no details regarding the parameter type and description. Therefore, I had developed a simple script (the `enhance-pyi.ipynb` in my forked [repo](https://github.com/I-am-Future/isaacgym-stubs-enhanced/tree/enhanced)), which parses the official html docs, and inserts the function and class docs into the current .pyi file. Here is a comparison between the original one and my enhanced one:

``` py
# gymapi.pyi, line 561-563

    def acquire_actor_root_state_tensor(self, arg0: Sim) -> Tensor: ...

    def acquire_dof_force_tensor(self, arg0: Sim) -> Tensor: ...
```

``` py
# gymapi-enhanced.pyi, line 649-675

    def acquire_actor_root_state_tensor(self, arg0: Sim) -> Tensor: ...
    ''' acquire_actor_root_state_tensor(self: Gym, arg0: Sim) -> Tensor
    Retrieves buffer for Actor root states.  The buffer has shape (num_actors, 13).
    State for each actor root contains position([0:3]), rotation([3:7]), linear velocity([7:10]), and angular velocity([10:13]).
    Parameters:
    param1 (Sim) - Simulation Handle
    
    Returns:
    GymTensor object containing buffer for actor root states
    
    Return type:
    isaacgym.gymapi.Tensor
    '''


    def acquire_dof_force_tensor(self, arg0: Sim) -> Tensor: ...
    ''' acquire_dof_force_tensor(self: Gym, arg0: Sim) -> Tensor
    Retrieves buffer for DOF forces. One force value per each DOF in simulation.
    Parameters:
    param1 (Sim) - Simulation Handle
    
    Returns:
    GymTensor object containing buffer for DOF forces
    
    Return type:
    isaacgym.gymapi.Tensor
    '''
```

As you can see, the docs are accompanied with the functions.  In IDEs such as VSCode, you can ctrl+left click the functions to jump into the .pyi file, and review the function descriptions in detail. I believe this can boost the developing speed even more. The following is a video demo:

https://github.com/yzqin/isaacgym-stubs/assets/74816944/ac7c718e-7fda-404e-90aa-301f7374021e

## Steps to run my script:

1. Clone my [repo](https://github.com/I-am-Future/isaacgym-stubs-enhanced/tree/enhanced) and change to `enhance` branch.

2. Open the `enhance-pyi.ipynb` and set the `HTML_PATH` in the last cell to where `isaacgym/docs/api/python/` locates.

3. Run the notebook, and the `gymapi-enhanced.pyi` would be produced. There is a copy [here](https://github.com/I-am-Future/isaacgym-stubs-enhanced/blob/enhanced/gymapi-enhanced.pyi) too.

## Additional comments

I understand directly merging my branch into your repo may destroy the file structure and clearity. Therefore, I am raising this issue to introduce you about my work for this project. If you are interested with my enhanced version of .pyi file, please reply to me, and we can discuss about further details. Thank you!! 😃

**Comment by yzqin** [comment]
Hi @I-am-Future 

This is excellent! The enhanced version appears to be very user-friendly and the documentation string is superb! Given that the enhanced version is strictly better than the original one, I suggest replacing the original `isaacgym-stubs/gymapi.pyi` with your `gymapi-enhanced.pyi` in your repository first. Then, you could create a pull request to merge it into this repository and officially become a contributor.

I will also update the readme to include a link to the `enhance-pyi.ipynb` in your forked repository. I believe this script could be beneficial for other Python packages generated using pybind11 as well.

**Comment by I-am-Future** [comment]
Hi Mr. @yzqin,

Thank you for your great comments to my work! I am really excited that I can contribute to your repo. Before that, I'll first make another check to ensure that my .pyi file's document strings are all correctly generated. Then, I will do the pull request. 

One of my concern is that my .pyi is only made for the preview version 4. But I can help to generate the remaining version's enhanced .pyi file in the future. 😄 

My `enhance-pyi.ipynb` script is originally designed for the Isaac Gym. But I think it probably can be used in other API reference's HTML page that generated by _Sphnix_ with minor revisions on the script. 😆

**Comment by yzqin** [comment]
Close this issue with PR #3
